### ISSUE TITLE
Another decoding approach to test

### ISSUE THREAD

**Issue by WojciechMula** [lemire/fastbase64#1]
Check performance of the code posted here https://github.com/WojciechMula/base64simd/issues/3

**Comment by lemire** [comment]
@WojciechMula Do you think that it is likely faster once ported to AVX2?

**Comment by WojciechMula** [comment]
@lemire Unlikely. But if it was faster then speed-up would be really small, few percents if any.

**Comment by lemire** [comment]
@WojciechMula  Could it be said to be more elegant?

**Comment by WojciechMula** [comment]
@lemire The algorithm itself is really tricky, an extra trick wouldn't make it nicer. :) I mean, to get a grasp why and how the algorithm works one needs some understanding. Then everything else is just an implementation detail.

**Comment by aqrit** [comment]
Replacing `blend` with `add` will remove 1 'uop' and 1 constant from the critical path.
and using `0x2F` instead of `0x0F` to mask nibbles will remove another constant. 

so it might be a tiny bit faster?

AFAIK, the bad char check will probably be done during the 10 cycles it takes for the multiply chain to complete, so there is little to be gained there.

on older processors, the multiply chain takes only 6 cycles and `movemask` is penalized when used with integer data... so there might be a small gain when using sse4.1

**Comment by WojciechMula** [comment]
@lemire I just pushed procedure by @aqrit, and checked performance on Skylake --- it's better, great job! The difference is not significant, however it's about 4-5% better than our current implementation.

Bare numbers: our procedure works at 0.25-0.26 cycles the new one works at 0.23-0.24.

**Comment by lemire** [comment]
@WojciechMula 

Amazing.

Did you push it to ``fastbase64`` as well so that we can update the gnuplot figures?

**Comment by WojciechMula** [comment]
Yes, I created a new branch: https://github.com/lemire/fastbase64/tree/another-decoding-proc
You can merge it to the master.

**Comment by lemire** [comment]
@aqrit 

So we can give you proper credit, would you share your real name (you don't have to)?

**Comment by lemire** [comment]
@WojciechMula  Merged. I have updated the figures.

**Comment by WojciechMula** [comment]
Great, thanks!
